<?php
/**
 * @category ClassyLlama
 * @package ClassyLlama_OrderComments
 * @copyright Copyright (c) 2018 ClassyLlama
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Sales\Block\Order\Invoice
 * @see \Magento\Sales\Block\Order\Invoice
 */
?>
<?php $order = $block->getOrder(); ?>
<?php if ($orderComment = $order->getOrderComment()): ?>
    <div class="block block-order-details-comments">
        <div class="block-title"><strong><?= /* @escapeNotVerified */ __('About Your Invoice') ?></strong></div>
        <div class="block-content">
            <dl class="order comments">
                <dt class="comment date"><?= /* @escapeNotVerified */ $block->formatDate($order->getCreatedAt(), \IntlDateFormatter::MEDIUM, true) ?></dt>
                <dd class="comment content"><?= $block->escapeHtml($orderComment) ?></dd>
            </dl>
        </div>
    </div>
<?php endif;?>
