<?php if ($slider = $block->getSlider()) : ?>
    <?php $slides = $slider->getSlides(); ?>
    <?php if (count($slides) > 0) : ?>
        <?php $sliderConfig = unserialize($slider->getSliderConfig()); ?>
        <div class="swiper-container easyslide-swiper-<?php echo $slider->getIdentifier() ?>" data-mage-init='{"easyslide":<?php echo $block->getSliderConfig() ?>}'>
            <div class="swiper-wrapper">
                <?php $i = 0; foreach ($slides as $slide) : ?>
                    <div class="swiper-slide">
                        <a href="<?php echo $slide['url'] ?>"
                            class="easyslide-link easyslide-link-<?php echo $i++ ?>"
                            target="<?php echo $slide['target'] ?>">
                            <img src="<?php echo $block->getImage($slide['image']); ?>"
                                alt="<?php echo $this->escapeHtml($slide['title']) ?>"
                            />
                        </a>
                        <?php if (!empty($slide['description'])) : ?>
                            <?php $className = implode(' ', [
                                'easyslide-description',
                                "easyslide-description-{$slide['desc_position']}",
                                "easyslide-background-{$slide['desc_background']}"
                            ]) ?>
                            <div class="<?php echo $className ?>">
                                <?php echo $block->getSlideDescription($slide['description']) ?>
                            </div>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>

            <?php $theme = isset($sliderConfig['theme']) ? $sliderConfig['theme'] : '' ?>
            <?php if ($sliderConfig['pagination']) : ?>
                <div class="swiper-pagination<?php echo $theme ? ' swiper-pagination-' . $theme : '' ?>"></div>
            <?php endif ?>

            <?php if ($sliderConfig['navigation']) : ?>
                <div class="swiper-button-prev<?php echo $theme ? ' swiper-button-' . $theme : '' ?>"></div>
                <div class="swiper-button-next<?php echo $theme ? ' swiper-button-' . $theme : '' ?>"></div>
            <?php endif ?>

            <?php if ($sliderConfig['scrollbar']) : ?>
                <div class="swiper-scrollbar"></div>
            <?php endif ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
