<?php
/**
 * @category ClassyLlama
 * @package ClassyLlama_OrderComments
 * @copyright Copyright (c) 2018 ClassyLlama
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Sales\Block\Adminhtml\Order\View\Tab\History $block */
?>
<?php $order = $block->getOrder(); ?>
<?php $orderComment = $order->getOrderComment(); ?>
<section class="admin__page-section edit-order-comments">
    <ul class="note-list">
        <?php if ($orderComment): ?>
            <li class="note-list-item">
                <span class="note-list-date"><?= /* @escapeNotVerified */ $block->getItemCreatedAt(['created_at' => $order->getCreatedAt()]) ?></span>
                <span class="note-list-time"><?= /* @escapeNotVerified */ $block->getItemCreatedAt(['created_at' => $order->getCreatedAt()], 'time') ?></span>
                <span class="note-list-status"><?= /* @escapeNotVerified */ __('Customer Comment') ?></span>
                <span class="note-list-customer">
                    <?= /* @escapeNotVerified */ __('Customer') ?>
                    <span class="note-list-customer-notified"><?= /* @escapeNotVerified */ __('Notified') ?></span>
                </span>
            </li>
        <?php endif; ?>
        <?php foreach ($block->getFullHistory() as $_item): ?>
            <li class="note-list-item">
                <span class="note-list-date"><?= /* @escapeNotVerified */ $block->getItemCreatedAt($_item) ?></span>
                <span class="note-list-time"><?= /* @escapeNotVerified */ $block->getItemCreatedAt($_item, 'time') ?></span>
                <span class="note-list-status"><?= /* @escapeNotVerified */ $block->getItemTitle($_item) ?></span>
                <?php if ($block->isItemNotified($_item, false)): ?>
                    <span class="note-list-customer">
                    <?= /* @escapeNotVerified */ __('Customer') ?>
                        <?php if ($block->isCustomerNotificationNotApplicable($_item)): ?>
                            <span class="note-list-customer-notapplicable"><?= /* @escapeNotVerified */ __('Notification Not Applicable') ?></span>
                        <?php elseif ($block->isItemNotified($_item)): ?>
                            <span class="note-list-customer-notified"><?= /* @escapeNotVerified */ __('Notified') ?></span>
                        <?php else: ?>
                            <span class="note-list-customer-not-notified"><?= /* @escapeNotVerified */ __('Not Notified') ?></span>
                        <?php endif; ?>
                </span>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
    <div class="edit-order-comments-block">
        <div class="edit-order-comments-block-title">
            <?= /* @escapeNotVerified */ __('Notes for this Order') ?>
        </div>
        <?php if ($orderComment): ?>
            <div class="comments-block-item">
                <div class="comments-block-item-comment">
                    <?= /* @escapeNotVerified */ $orderComment ?>
                </div>
                <span class="comments-block-item-date-time">
                    <?= /* @escapeNotVerified */ __('Comment added') ?>
                    <?= /* @escapeNotVerified */ $block->getItemCreatedAt(['created_at' => $order->getCreatedAt()]) ?>
                    <?= /* @escapeNotVerified */ $block->getItemCreatedAt(['created_at' => $order->getCreatedAt()], 'time') ?>
                </span>
            </div>
        <?php endif; ?>
        <?php foreach ($block->getFullHistory() as $_item): ?>
            <?php if ($_comment = $block->getItemComment($_item)): ?>
                <div class="comments-block-item">
                    <div class="comments-block-item-comment">
                        <?= /* @escapeNotVerified */ $_comment ?>
                    </div>
                    <span class="comments-block-item-date-time">
                        <?= /* @escapeNotVerified */ __('Comment added') ?>
                        <?= /* @escapeNotVerified */ $block->getItemCreatedAt($_item) ?>
                        <?= /* @escapeNotVerified */ $block->getItemCreatedAt($_item, 'time') ?>
                    </span>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</section>
