<?php
    use Magento\Framework\App\Action\Action;

    $list = $this->getParentBlock();
    $_product = $this->getProduct();
    $position = $this->getPosition();
    $pos = $list->getPositioned();
    $viewMode = $list->getMode();
?>
<div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
        <?php if ($_product->isSaleable()): ?>
            <?php $postParams = $list->getAddToCartPostParams($_product); ?>
            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                <?php echo $list->getBlockHtml('formkey')?>
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                        class="action tocart primary">
                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                </button>
            </form>
        <?php else: ?>
            <?php if ($_product->getIsSalable()): ?>
                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
            <?php else: ?>
                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
            <?php endif; ?>
        <?php endif; ?>
    </div>
    <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
            <a href="#"
               class="action towishlist"
               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
               data-post='<?php /* @escapeNotVerified */ echo $list->getAddToWishlistParams($_product); ?>'
               data-action="add-to-wishlist"
               role="button">
                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
            </a>
        <?php endif; ?>
        <?php
        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
        ?>
        <a href="#"
           class="action tocompare"
           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
           role="button">
            <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
        </a>
    </div>
</div>
