<script id="swissup-ajaxsearch-product-template-header" type="text/x-magento-template">
    <h4><?php echo __('Products') ?></h4>
</script>
<script id="swissup-ajaxsearch-product-template" type="text/x-magento-template">
    <div class="product-item-info">
        <a href="<%= item.product_url %>" class="product photo product-item-photo" tabindex="-1">
        <%= item.image %>
        </a>
        <div class="product details product-item-details">
            <strong class="product name product-item-name">
                <a class="product-item-link" href="<%= item.product_url %>"><%= item.title %></a>
            </strong>
            <div class="price-box price-final_price">
                <span class="price-container price-final_price tax weee">
                    <span class="price-wrapper">
                        <span class="price"><?php echo __('Price') ?> : <%= formatPrice(item.final_price ? item.final_price : item.max_price, priceFormat) %></span>
                    </span>
                </span>
            </div>
            <div class="product-info-stock-sku">
                <div class="product attibute sku">
                    <div itemprop="sku" class="value"><?php echo __('SKU') ?> : <%= item.sku %></div>
                </div>
            </div>
        </div>
    </div>
</script>