<?php
$elementName = $block->getElement()->getName() . '[images]';
$formName = $block->getFormName();
?>
<div id="images"
     class="gallery"
     data-images="<?= $block->escapeHtml($block->getImagesJson()) ?>"
     data-types="<?= $block->escapeHtml(
         $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getImageTypes())
     ) ?>"
    >
    <?php if (!$block->getElement()->getReadonly()) {?>
        <div class="image image-placeholder">
            <?= $block->getUploaderHtml() ?>
            <div class="product-image-wrapper">
                <p class="image-placeholder-text">
                    <?= /* @escapeNotVerified */ __('Browse to find or drag image here') ?>
                </p>
            </div>
        </div>
    <?php } ?>
    <?php foreach ($block->getImageTypes() as $typeData) {
    ?>
        <input name="<?= $block->escapeHtml($typeData['name']) ?>"
               data-form-part="<?= /* @escapeNotVerified */ $formName ?>"
               class="image-<?= $block->escapeHtml($typeData['code']) ?>"
               type="hidden"
               value="<?= $block->escapeHtml($typeData['value']) ?>"/>
    <?php

} ?>
</div>
<script>
    require([
        'jquery',
        'uiRegistry',
        'productGallery',
        'Swissup_Lightboxpro/js/widget/gallery',
        'text!Swissup_Lightboxpro/templates/gallery.html',
        'text!Swissup_Lightboxpro/templates/dialog-container.html',
        'text!Swissup_Lightboxpro/templates/dialog.html'
    ], function ($, registry, productGallery, lightboxproWidget, galleryTmpl, dialogContainerTmpl, dialogTmpl) {
        $(function () {
            registry.set('swissup.lightboxpro.gallery.widget', lightboxproWidget);

            var elem = $('#images')
                .append($(galleryTmpl), $(dialogContainerTmpl), $(dialogTmpl))
                .productGallery({
                    "template": "#images-template",
                    "parentComponent": "swissup.lightboxpro.gallery.widget"
                });
        });
    });
</script>
<script>
    jQuery('body').trigger('contentUpdated');
</script>
