<div id="<?= $block->getHtmlId() ?>" class="uploader">
    <div class="fileinput-button form-buttons button">
        <span><?= /* @escapeNotVerified */ __('Browse Files...') ?></span>
        <input id="fileupload" type="file" name="<?= /* @escapeNotVerified */ $block->getConfig()->getFileField() ?>"
            data-url="<?= /* @escapeNotVerified */ $block->getConfig()->getUrl() ?>" multiple="multiple" />
    </div>
    <div class="clear"></div>
    <script>
        require([
            'jquery',
            'mediaUploader',
            'text!Swissup_Lightboxpro/templates/uploader.html'
        ], function ($, mediaUploader, tmpl) {
            $(function () {
                var elem = $(<?= $block->getHtmlId() ?>)
                    .append($(tmpl))
                    .mediaUploader({
                        "maxFileSize": <?= /* @escapeNotVerified */ $block->getFileSizeService()->getMaxFileSize() ?>,
                        "maxWidth":<?= /* @escapeNotVerified */ \Magento\Framework\File\Uploader::MAX_IMAGE_WIDTH ?> ,
                        "maxHeight": <?= /* @escapeNotVerified */ \Magento\Framework\File\Uploader::MAX_IMAGE_HEIGHT ?>
                });
            });
        });
    </script>
</div>
