<?php
/**
 * @category UAE
 * @package UAE_BreadcrumbsFix
 * @copyright Copyright (c) 2018 ClassyLlama
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
/** @var \UAE\BreadcrumbsFix\ViewModel\Product\Breadcrumbs $customViewModel */
$customViewModel = $block->getData('customViewModel');
?>
<div class="breadcrumbs" data-mage-init='{
    "breadcrumbs": {
        "categoryUrlSuffix": "<?= $block->escapeHtml($viewModel->getCategoryUrlSuffix()); ?>",
        "useCategoryPathInUrl": <?= (int)$viewModel->isCategoryUsedInProductUrl(); ?>,
        "product": "<?= $block->escapeHtml($viewModel->getProductName()); ?>",
        "breadcrumbPath": <?= /* @escapeNotVerified */ $customViewModel->getBreadcrumbPath() ?>
    }
}'>
</div>
