<?php
    $method = $block->getCollectionMethod() ? $block->getCollectionMethod() : 'getProductCollection';
?>

<?php if (($_products = $block->{$method}()) && $_products->getSize()): ?>
    <div class="block widget block-products-names">
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $block->getTitle() ?></strong>
        </div>
        <div class="block-content">
            <?php $suffix = $block->getNameInLayout(); ?>
            <ol id="widget-products-<?php /* @escapeNotVerified */ echo $suffix; ?>" class="product-items product-items-names">
                <?php foreach ($_products->getItems() as $_product): ?>
                    <li class="product-item">
                        <strong class="product-item-name">
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>"
                               title="<?php /* @escapeNotVerified */ echo $block->stripTags($_product->getName(), null, true) ?>)"
                               class="product-item-link">
                                <?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>
