<?php
/**
 * @copyright   Copyright (c) 2018 Classy Llama Studios, LLC
 */
?>
<?php if ($block->isPossibleOnepageCheckout()):?>
    <button type="button"
            data-role="proceed-to-checkout"
            title="<?php /* @escapeNotVerified */ echo __('Save Cart as Quote') ?>"
            data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= $block->getCheckoutUrl() . '?quote=true'; ?>"}}'
            class="action checkout<?php echo($block->isDisabled()) ? ' disabled' : ''; ?>"
            <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
        <span><?php /* @escapeNotVerified */ echo __('Save Cart as Quote') ?></span>
    </button>
<?php endif?>
