<?php if ($block->getConfig('enabled') && ($items = $block->getItems()) && ($block->getItems()->getSize() > 0)) : ?>
    <div class="block soldtogether-customer-slick block-carousel">
        <div class="block-title title">
            <strong id="block-soldtogether-customer-heading" role="heading" aria-level="2">
                <?php echo __('Customers Who Bought This Item Also Bought') ?>
            </strong>
        </div>
        <div class="block-content">
            <div data-mage-init='{"slick": {"slidesToShow": 5, "slidesToScroll": 5, "dots": false,
                "responsive": [
                    {"breakpoint": 1024, "settings": { "slidesToShow": 4, "slidesToScroll": 4 }},
                    {"breakpoint": 770, "settings": { "slidesToShow": 3, "slidesToScroll": 3 }},
                    {"breakpoint": 600, "settings": { "slidesToShow": 2, "slidesToScroll": 2 }},
                    {"breakpoint": 480,"settings": { "slidesToShow": 1, "slidesToScroll": 1}}
                ],
              "autoplay": false}}'>
                <?php foreach ($items as $_item) : ?>
                    <div style="margin: 15px;">
                        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                            <?php echo $block->getImage($_item, 'category_page_grid')->toHtml(); ?>
                        </a>
                        <div class="product details product-item-details">
                            <strong class="product name product-item-name" style="text-align: center;">
                                <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                <?php echo $block->escapeHtml($_item->getName()) ?></a>
                            </strong>
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
                            <?php if (!$block->getHideCheckboxes() && !$_item->getRequiredOptions() && !$_item->getData('has_options')): ?>
                                <div class="field choice">
                                    <input type="checkbox" class="checkbox soldtogether-customer" id="soldtogether-customer-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>" name="soldtogether_customer[]" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                    <label class="label" for="soldtogether-customer-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></label>
                                </div>
                            <?php endif; ?>
                        </div>

                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<script>
require([
    'jquery'
], function ($) {
    $(function () {
        $( ".soldtogether-customer" ).change(function() {
            if ($(this).is(":checked")) {
                var relatedItems = $("#related-products-field").val();
                if (relatedItems.length > 0) {
                    var items = relatedItems.split(",");
                    items.push($(this).val());
                    $("#related-products-field").val(items.join(','));
                } else {
                    $("#related-products-field").val($(this).val());
                }
            } else {
                var relatedItems = $("#related-products-field").val();
                if (relatedItems.length > 0) {
                    var items = relatedItems.split(",");
                    for(var i = items.length; i--;) {
                        if(items[i] === $(this).val()) {
                            items.splice(i, 1);
                        }
                    }
                    $("#related-products-field").val(items.join(','));
                }
            }
        });
    });
});
</script>
<?php endif; ?>
