<?php
/**
 * @category    ClassyLlama
 * @copyright   Copyright (c) 2018 Classy Llama
 */
/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';

if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<?php // EDIT: Add main-nav classes ?>
<li class="authorization-link level0" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?> class="level-top">
        <?= $block->escapeHtml($block->getLabel()) ?>
    </a>
</li>
