<?php
/**
 * @copyright   Copyright (c) 2018 Classy Llama Studios, LLC
 */

/** @var \UAE\GroupedProduct\Block\Product\Review $block */

$product = $block->getProduct();
?>
<div id="product-review-container-<?= $product->getId() ?>" data-role="product-review"></div>
<script type="text/x-magento-init">
    {
        "*": {
            "UAE_GroupedProduct/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->escapeUrl($block->getProductReviewUrl())) ?>",
                "reviewsTabSelector": "#tab-label-reviews_simple-<?= $product->getId() ?>",
                "productId": "<?= $product->getId() ?>"
            }
        }
    }
</script>
