<?php
/**
 * @category    ClassyLlama
 * @copyright   Copyright (c) 2018 Classy Llama
 */
/*
* Updated by UAE
* 12/06/2018
* JS made by Klevu
*/
?>
<script type="text/javascript">
    var klevu_uc = { 
   
        showLandingPageData: function (product) {
            var toReturn = '',
                toAppendwithSalePrice = '',
                priceWithCurrency = '',
                appendCurrencyAtLast = false,
                salepriceClass = 'kuSalePrice',
                priceFormatter, priceToSet,
                showToLabel = false,
                additionalParams = '',
                landingSequence,
                landingItemParam = '',
                keywords = document.getElementById('searchedKeyword').value,
                trackingParams = "";

            product = klevu_productCustomizations(product);
            landingSequence = product.children ? product.children.toUpperCase().split(" ") : [];

            if (landingSequence.indexOf(keywords.toUpperCase()) !== -1) {
                landingItemParam = '?item=' + keywords.toUpperCase();
            }

            if (product.productImage.trim().length === 0) {
                product.productImage = klevu_userOptions.noImageUrl;
            }

            if (klevu_userOptions.openProductClicksInNewWindow) {
                additionalParams = ' target="_blank"';
            } else {
                additionalParams = ' onclick="klevu_analytics.stopClickDefault( event );"';
            }
            trackingParams = '{' +
                'data: {' +
                'code: \'' + escape(product.productCode) + '\',' +
                'url: \'' + escape(product.productUrl) + '\',' +
                'name: \'' + escape(product.productName) + '\',' +
                'salePrice: \'' + escape(product.salePrice) + '\',' +
                'rating: \'' + escape(product.rating) + '\',' +
                'position: ' + product.productPosition + ',' +
                'category: \'' + escape(product.category) + '\'' +
                '},' +
                'apiKey: null,' +
                'keywordsLP: \'' + escape(keywords) + '\'' +
                '}';
            
            toReturn += '<li>';

            toReturn += '<div class="klevuImgWrap"><a href="' + product.productUrl.replace(/"/g, "%22") +
                landingItemParam + '" target="_blank" ';
            if (klevu_commons.isMobileDevice()) {
                toReturn += ' onclick="return klevu_analytics.trackClickedProduct(event, ' + trackingParams + ');" >';
            } else {
                toReturn += ' onmousedown="return klevu_analytics.trackClickedProduct(event, ' + trackingParams + ');" ' + additionalParams + '>';
            }

            toReturn += '<img src="' +
                product.productImage + '" onerror="this.onerror=null;this.src=\'' +
                klevu_userOptions.noImageUrl + '\';" alt="' + klevu_commons.escapeHtml(product.productName) + '"/></a></div>';
            if ('undefined' !== typeof klevu_showDiscountBadge &&
                klevu_showDiscountBadge && product.discount != '' &&
                product.discount != '0' && product.discount != '0.0') {
                if (klevu_uiLabels.discountBadgeText.indexOf("#") === -1) {
                    toReturn += '<div class="kuDiscountBadge">' +
                        klevu_uiLabels.discountBadgeText + ' ' +
                        Number(product.discount).toFixed(0) +
                        '%</div>';
                } else {
                    toReturn += '<div class="kuDiscountBadge">' +
                        klevu_uiLabels.discountBadgeText.replace("#", Number(product.discount).toFixed(0) + "%") +
                        '</div>';
                }
            }
            toReturn += '<div class="kuNameDesc">';
            toReturn += '<div class="kuName"><a href="' + product.productUrl.replace(/"/g, "%22") + landingItemParam +
                '" target="_blank" ';
            if (klevu_commons.isMobileDevice()) {
                toReturn += ' onclick="return klevu_analytics.trackClickedProduct(event, ' + trackingParams + ');" >';
            } else {
                toReturn += ' onmousedown="return klevu_analytics.trackClickedProduct(event, ' + trackingParams + ');" ' + additionalParams + '>';
            }
            toReturn += product.productName + '</a></div>';
            toReturn += '<div class="kuDesc">' + product.productDescription + '</div>';
            if (product.rating.trim().length > 0 && !isNaN(Number(product.rating)) &&
                Number(product.rating) <= 5 && Number(product.rating) >= 0) {
                var starWidth = 20 * Number(product.rating);
                toReturn += '<div class="kuStarsSmall">' +
                    '<div class="kuRating" style="width:' + starWidth +
                    '%;"></div></div>';
            }
            toReturn += '</div>';

            if (product.children && product.children != '') {

              toReturn += '<div class="startingAt"> Starting At</div>';

            }

            toReturn += '<div class="kuPrice">';
            if (klevu_showPrices) {
                if (klevu_userOptions.showOnlyOriginalAndSalePrices) {
                    toReturn += klevu_commons.showOriginalAndSalePrices('LANDING', product,
                        salepriceClass, 'kuSalePrice kuSpecialPrice');
                } else {
                    toReturn += klevu_commons.showProductPrices('LANDING', product,
                        salepriceClass, 'kuSalePrice kuSpecialPrice');
                }
            }

            if (klevu_userOptions.vatCaption.trim().length > 0) {
                toReturn += '<div class="klevu-vat-caption">(' + klevu_userOptions.vatCaption + ')</div>';
            }

            if (product.totalProductVariants && product.totalProductVariants != '0') {
                if (klevu_uiLabels.variants.indexOf("#") === -1) {
                    toReturn += '<div class="klevu-variants">+' + product.totalProductVariants +
                        ' ' + klevu_uiLabels.variants + '</div>';
                } else {
                    toReturn += '<div class="klevu-variants">' +
                        klevu_uiLabels.variants.replace("#", product.totalProductVariants) + '</div>';
                }
            }
            if (klevu_userOptions.outOfStockCaption.trim().length > 0) {
                if ((product.inStock) && product.inStock === 'no') {
                    toReturn += '<div class="klevu-out-of-stock">' +
                        klevu_userOptions.outOfStockCaption + '</div>';
                }
            }

            toReturn += '</div>';
            if (klevu_commons.showAddToCartButton(product.inStock, product.hideAddToCart)) {
                if (!(product.isCustomOptionsAvailable && product.isCustomOptionsAvailable === "yes") &&
                    (!product.totalProductVariants || product.totalProductVariants == '0')) {
                    toReturn += '<div class="kuAddtocart">' +
                        '<input type="text" name="klevu-qty" id="klevu-qty-' +
                        escape(product.productCode) + '" placeholder="' +
                        klevu_uiLabels.addToCartPlaceholder + '"/>' +
                        '<a href="javascript:klevu_lpSendProductToCart(\'' +
                        escape(product.productCode) + '\', \'' +
                        escape(product.productUrl) + '\', \'klevu-qty-' +
                        escape(product.productCode) + '\');" ' +
                        'class="kuAddtocartBtn">' + klevu_userOptions.addToCartButton + '</a>' +
                        '</div>';
                } else {
                    toReturn += '<div class="kuAddtocart">' +
                        '<a href="' + product.productUrl.replace(/"/g, "%22") + landingItemParam +
                        '" class="kuAddtocartBtn">' + klevu_userOptions.addToCartButton + '</a>' +
                        '</div>';
                }
                toReturn += '<div class="klevu-clearboth-listview"></div>';
            }
            toReturn += '<div class="kuClearLeft"></div>';
            toReturn += '</li>';

            return toReturn;
        },

        showAutocompleteProducts: function (product) {
            var productHtml = '',
                trackingParams = '',
                imgAlt,
                imgAltDiv = document.createElement('div'),
                sequence,
                landingItemParam = '';

            product = klevu_productCustomizations(product);
            sequence = product.children ? product.children.toUpperCase().split(" ") : [];

            if (sequence.indexOf(klevu_searchedTerm.toUpperCase()) !== -1) {
                landingItemParam = '?item=' + klevu_searchedTerm.toUpperCase();
            }

            if (product.productImage.trim().length === 0) {
                product.productImage = klevu_userOptions.noImageUrl;
            }
            if (klevu_userOptions.openProductClicksInNewWindow) {
                additionalParams = ' target="_blank"';
            } else {
                additionalParams = ' onclick="klevu_analytics.stopClickDefault( event );"';
            }
            trackingParams = '{' +
                'data: {' +
                'code: \'' + escape(product.productCode) + '\',' +
                'url: \'' + escape(product.productUrl) + '\',' +
                'name: \'' + escape(product.productName) + '\',' +
                'salePrice: \'' + escape(product.salePrice) + '\',' +
                'rating: \'' + escape(product.rating) + '\',' +
                'position: ' + product.productPosition + ',' +
                'category: \'' + escape(product.category) + '\'' +
                '}' +
                '}';
            imgAltDiv.innerHTML = product.productName;
            imgAlt = imgAltDiv.textContent || imgAltDiv.innerText || "";
            productHtml += '<li>';


            productHtml += '<a href="' + product.productUrl.replace(/"/g, "%22") + landingItemParam + '" class="klevu-result-box-l2" ';
            if (klevu_commons.isMobileDevice()) {
                productHtml += ' onclick="return  klevu_analytics.trackClickedProduct(event, ' + trackingParams + ');"  >';
            } else {
                productHtml += ' onmousedown="return  klevu_analytics.trackClickedProduct(event, ' + trackingParams + ');" ' +
                    additionalParams + ' >';
            }

            productHtml += '<div class="klevu-img-wrap-l2"><img src="' + product.productImage +
                '" onerror="this.onerror=null;this.src=\'' + klevu_userOptions.noImageUrl +
                '\';" alt="' + klevu_commons.escapeHtml(imgAlt) + '" /></div>';
            if ('undefined' !== typeof klevu_showDiscountBadge &&
                klevu_showDiscountBadge && product.discount != '' &&
                product.discount != '0' && product.discount != '0.0') {
                if (klevu_uiLabels.discountBadgeText.indexOf("#") === -1) {
                    productHtml += '<div class="klevu-discount-badge-l2">' +
                        klevu_uiLabels.discountBadgeText + ' ' + Number(product.discount).toFixed(0) +
                        '%</div>';
                } else {
                    productHtml += '<div class="klevu-discount-badge-l2">' +
                        klevu_uiLabels.discountBadgeText.replace("#", Number(product.discount).toFixed(0) + "%") +
                        '</div>';

                }
            }
            productHtml += '<div class="klevu-name-desc-l2">';
            productHtml += '<div class="klevu-name-l2">' + product.productName + '</div>' +
                '<div class="klevu-desc-l2">' + product.productDescription + '</div>';

            
            if (klevu_showPrices) {
                productHtml += '<div class="klevu-price-l2">';
                if (klevu_userOptions.showOnlyOriginalAndSalePrices) {
                    productHtml += klevu_commons.showOriginalAndSalePrices('SLIM', product, 'klevu-saleprice-l2',
                        'klevu-saleprice-l2 klevu-special-price-l2');
                } else {
                    productHtml += klevu_commons.showProductPrices('SLIM', product, 'klevu-saleprice-l2',
                        'klevu-saleprice-l2 klevu-special-price-l2');
                }
                if (klevu_userOptions.vatCaption.trim().length > 0) {
                    productHtml += '<span class="klevu-vat-caption-l2">(' +
                        klevu_userOptions.vatCaption + ')</span>';
                }
                productHtml += '</div>';
            }
            if (product.rating.trim().length > 0 && !isNaN(Number(product.rating)) &&
                Number(product.rating) <= 5 && Number(product.rating) >= 0) {
                var starWidth = 20 * Number(product.rating);
                productHtml += '<div class="klevu-stars-small-l2">' +
                    '<div class="klevu-rating-l2" style="width:' + starWidth +
                    '%;"></div></div>';
            }
            if (klevu_userOptions.outOfStockCaption.trim().length > 0) {
                if (product.inStock && product.inStock === 'no') {
                    productHtml += '<div class="klevu-out-of-stock-l2">' +
                        klevu_userOptions.outOfStockCaption + '</div>';
                }
            }
            productHtml += '</div><div class="klevu-clear-left"></div></a></li>';
            return productHtml;
        },

        showResultsData: function (response, callFrom) {
            var doc = document, noOtherDataAvailable = true,
                klevuSearchNoResult = doc.getElementById('klevuSearchNoResults'),
                arrowDiv = doc.getElementById('klevuArrow');
                
            
            this.hideLoader();
            if (klevu_searchedTerm.length === 0) {
                return;
            }

            var redirectUrl = klevu_commons.getRedirectUrlForSearchedTerm(klevu_searchedTerm);
            
            if (klevuSearchNoResult) {
                klevuSearchNoResult.style.display = "none";
            }
            
            if (klevu_showAdvancedAutosuggestionLayout) {
                this.showAdvancedAutoSuggestions(response.autoComplete, noOtherDataAvailable, response.meta);
            } 
            else {
                this.showAutoSuggestions(response.autoComplete, response.meta);
                this.showCmsContent(response.pages);
                this.showCategories(response.categories);

                if ((response.autoComplete && response.autoComplete.length > 0) ||
                    (response.categories && response.categories.length > 0) ||
                    (response.pages && response.pages.length > 0)) {
                    noOtherDataAvailable = false;
                }
                
                this.showProducts(response.meta, response.result, noOtherDataAvailable, response.popularProducts);

                if (!noOtherDataAvailable || response.result.length > 0) {
                    klevu_commons.showBannerAdForGivenTerm(klevu_searchedTerm);
                } else {
                    klevu_commons.showBannerAdForGivenTerm("");
                }
            }

            if (klevu_activeSearchBox.form) {
                if(redirectUrl !== null) {
                    klevu_activeSearchBox.form.action = redirectUrl;
                    klevu_activeSearchBox.form.method = "post";
                    if (doc.getElementById("klevu-loader-2")) {
                        doc.getElementById("klevu-loader-2").style.display = "none";
                    }
                }
                else if(response.result.length === 1) {
                    var childSkus = response.result[0].children,
                        directUrl = response.result[0].url,
                        directSku = response.result[0].sku,
                        sequence = childSkus ? childSkus.toUpperCase().split(" ") : [],
                        upperCaseSearchedTerm = klevu_searchedTerm.toUpperCase();

                    //If Exact Child SKU Match
                    if (sequence.indexOf(upperCaseSearchedTerm) !== -1) {
                        klevu_activeSearchBox.form.action = directUrl + '?item=' + upperCaseSearchedTerm;
                        klevu_activeSearchBox.form.method = "post";
                        if (doc.getElementById("klevu-loader-2")) {
                            doc.getElementById("klevu-loader-2").style.display = "none";
                        }
                    }
                    // Single Result Exact SKU Match
                    else if (directSku) {
                        var otherMatch = directSku.toUpperCase().replace(/[^A-Z0-9]/ig, "");
                        if (otherMatch === upperCaseSearchedTerm.replace(/[^A-Z0-9]/ig, "") ) {
                            klevu_activeSearchBox.form.action = directUrl;
                            klevu_activeSearchBox.form.method = "post";
                            if (doc.getElementById("klevu-loader-2")) {
                                doc.getElementById("klevu-loader-2").style.display = "none";
                            }
                        }                  
                    }
                    else if (klevu_activeSearchBox.form) {
                        klevu_activeSearchBox.form.method = "get";
                    }
                }
                doc.getElementById('klevuSearchingArea').style.cssText += ";display : block !important;";
                if (arrowDiv) {
                    arrowDiv.style.display = "none"; 
                }
            }
        }
}
</script>
