<?php
/**
 * Based on Magento_Reports::widget/viewed/column/viewed_names_list.phtml
 * @var $block \Magento\Reports\Block\Product\Viewed
 */
?>
<div class="block widget block-viewed-products-names">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Recently Viewed') ?></strong>
    </div>
    <div class="block-content">
        <?php if (($_products = $block->getRecentlyViewedProducts()) && $_products->getSize()): ?>
            <?php $suffix = $block->getNameInLayout(); ?>
            <ol id="widget-viewed-<?php /* @escapeNotVerified */ echo $suffix; ?>" class="product-items product-items-names">
            <?php foreach ($_products as $_product): ?>
                <li class="product-item">
                    <strong class="product-item-name">
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-item-link">
                            <?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getName(), 'name') ?>
                        </a>
                    </strong>
                </li>
            <?php endforeach; ?>
            </ol>
        <?php else: ?>
            <div class="content"><?php echo __('You have not viewed any product yet') ?></div>
        <?php endif; ?>
    </div>
</div>
