<?php
// @codingStandardsIgnoreFile

/**
 * @var \Swissup\ThemeEditorArgentoLuxury\Block\Html\Header\LogoAlt $block
 */
?>
<?php if ($block->isHomePage()):?>
    <strong class="logo logo-alt">
        <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
             alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
             <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
    </strong>
<?php endif; ?>
