<?php
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Swissup\Highlight\Block\Product\Abstract
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $title = $block->getTitle();
    $items = $block->getProductCollection()->getItems();
    $helper = $this->helper('Magento\Catalog\Helper\Output');
}
?>

<?php if ($exist):?>
    <div class="block widget block-highlight highlight-list <?php /* @escapeNotVerified */ echo $block->getCssClass(); ?>">
        <?php if ($title): ?>
            <div class="block-title">
                <strong role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
            </div>
        <?php endif; ?>
        <div class="block-content">
            <ol class="product-items product-items-images">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                    <li class="product-item">
                        <a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>"
                           title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
                            <?php /* new_products_images_only_widget */ ?>
                            <?php echo $block->getImage($_item, 'new_products_images_only_widget')->toHtml(); ?>
                        </a>
                    </li>
                <?php endforeach ?>
            </ol>
            <?php echo $block->getPagerHtml() ?>

            <?php if ($block->getShowPageLink()) : ?>
                <div class="actions-toolbar">
                    <a class="action view"
                        href="<?php echo $block->escapeHtml($block->getPageUrl()) ?>"
                        title="<?php echo $block->escapeHtml($block->getPageLinkTitle()) ?>"
                        ><span><?php echo $block->escapeHtml($block->getPageLinkTitle()) ?></span></a>
                </div>
            <?php endif ?>
        </div>
    </div>
<?php endif;?>
