<?php
    $_banners = $this->getBanners();
    if (!$_banners || !count($_banners)):
        return;
    endif;
?>

<div class="<?php echo $this->getPlaceholderClassName() ?>">
    <div class="easybanner-placeholder-wrapper">
    <?php foreach ($_banners as $_banner): ?>
        <?php
            $bannerBlock = $this->getLayout()->createBlock('Swissup\Easybanner\Block\Banner');
            $bannerBlock->setBannerObject($_banner);
            echo $bannerBlock->toHtml();
        ?>
    <?php endforeach ?>
    </div>
</div>
