<?php
    $_banners = $block->getBanners();
    $_conditions = [];
    if (!count($_banners)) {
        return;
    }
?>

<div class="easybanner-popup-banner" style="display:none;">
    <?php foreach ($_banners as $_banner): ?>
        <?php
            $bannerBlock = $this->getLayout()->createBlock('Swissup\Easybanner\Block\Banner');
            $bannerBlock->setBannerObject($_banner);

            $html = $bannerBlock->toHtml();
            if (empty($html)) {
                continue;
            }
        ?>

        <?php echo $html ?>

        <?php $_conditions[$_banner->getHtmlId()] = $_banner->getJsConditions(); ?>
    <?php endforeach ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "easybanner": <?php echo $this->getJsonConditions($_conditions) ?>
        }
    }
</script>
