<?php
/**
 * @category    ClassyLlama
 * @copyright   Copyright (c) 2018 Classy Llama
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart update">
        <div class="box-tocart-inner">
            <?php // EDIT: Add back-to-top button for grouped PDP ?>
            <a href="#" class="back_to_top"><?= __('Scroll to top') ?></a>
            <script type="text/javascript">
                require(['jquery'], function ($) {
                    'use strict';
                    $('.back_to_top').on('click', function(e) {
                        e.preventDefault();
                        $('html, body').animate({scrollTop:0}, 300);
                    });
                });
            </script>
            <fieldset class="fieldset">
                <?php if ($block->shouldRenderQuantity()): ?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                        <div class="control">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   value=""
                                   title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                   class="input-text qty"
                                   data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                            class="action primary tocart"
                            id="product-updatecart-button">
                        <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                    </button>
                    <?= $block->getChildHtml('', true) ?>
                </div>
            </fieldset>
        </div>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>
