<?php
// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Swissup\Ajaxsearch\Block\Init */
/** @var $helper \Magento\Search\Helper\Data */
$ajaxActionUrl = $block->getUrl('search/ajax/suggest', ['_current' => true, '_query' => ['q' => "_QUERY"]]);
$helper = $this->helper('Magento\Search\Helper\Data');
$minQueryLength = $helper->getMinQueryLength() ? $helper->getMinQueryLength() : 3;
/** @var $ajaxsearchHelper \Swissup\Ajaxsearch\Helper\Data */
$ajaxsearchHelper = $this->helper('Swissup\Ajaxsearch\Helper\Data');
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "swissup-ajaxsearch": {
                    "component": "Ajaxsearch",
                    "options": {
                        "elementId": "#search",
                        "url": "<?php echo $ajaxActionUrl;?>",
                        "wildcard": "_QUERY",
                        "classes": {
                            "container": ".block-swissup-ajaxsearch",
                            "additional": "<?php /* @escapeNotVerified */ echo  $ajaxsearchHelper->getAdditionalCssClass();?>",
                            "mask": ".ajaxsearch-mask",
                            "formLabel": "#search_mini_form .search label"
                        },
                        "templates": {
                            "autocomplete": "#swissup-ajaxsearch-autocomplete-template",
                            "product": "#swissup-ajaxsearch-product-template",
                            "page": "#swissup-ajaxsearch-page-template",
                            "category": "#swissup-ajaxsearch-category-template",
                            "notFound": "#swissup-ajaxsearch-template-not-found"
                        },
                        "loader": {
                            "container": ".block-swissup-ajaxsearch .actions .action",
                            "loaderImage": "<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
                        },
                        "typeahead": {
                            "options": {
                                "highlight": <?php /* @escapeNotVerified */ echo $block->isHighligth() ? 'true' : 'false';?>,
                                "hint": <?php /* @escapeNotVerified */ echo $block->isHint() ? 'true' : 'false';?>,
                                "minLength": <?php /* @escapeNotVerified */ echo $minQueryLength ;?>,
                                "classNames": <?php /* @escapeNotVerified */ echo $block->getClassNames()?>
                            },
                            "limit": <?php /* @escapeNotVerified */ echo $block->getLimit()?>
                        },
                        "settings": <?php /* @escapeNotVerified */ echo $block->getJsonConfig()?>
                    }
                }
            }
        }
    }
}
</script>
