<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Adminhtml\Product\Helper\Form\Gallery\Content */
$elementName = $block->getElement()->getName() . '[images]';
$formName = 'edit_form';
?>
<div id="<?php echo $block->getHtmlId() ?>"
     class="gallery"
     data-mage-init='{"slideGallery":{"template":"#<?php echo $block->getHtmlId() ?>-template"}}'
     data-parent-component="<?php echo $block->escapeHtml($block->getData('config/parentComponent')) ?>"
     data-images="<?php echo $block->escapeHtml($block->getImagesJson()) ?>"
     data-types="<?php echo $block->escapeHtml(
         $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getImageTypes())
     ) ?>"
    >
    <?php if (!$block->getElement()->getReadonly()) {?>
        <div class="image image-placeholder">
            <?php echo $block->getUploaderHtml(); ?>
            <div class="product-image-wrapper">
                <p class="image-placeholder-text">
                    <?php /* @escapeNotVerified */ echo __('Browse to find or drag image here'); ?>
                </p>
            </div>
        </div>
    <?php } ?>
    <?php foreach ($block->getImageTypes() as $typeData) {
    ?>
        <input name="<?php echo $block->escapeHtml($typeData['name']) ?>"
               data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
               class="image-<?php echo $block->escapeHtml($typeData['code']) ?>"
               type="hidden"
               value="<?php echo $block->escapeHtml($typeData['value']) ?>"/>
    <?php

} ?>

    <script id="<?php echo $block->getHtmlId() ?>-template" type="text/x-magento-template">
        <div class="image item<% if (data.disabled == 1) { %> hidden-for-front<% } %>"
             data-role="image">
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][position]"
                   value="<%- data.position %>"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   class="position"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][file]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.file %>"/>
           <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][slide_id]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.slide_id %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][is_active]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<% if (!data.slide_id) { %>1<% } else { %><%- data.is_active %><% } %>"/>
           <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][title]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.title %>"/>
           <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][link]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.link %>"/>
           <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][target]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.target %>"/>
           <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][description]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.description %>"/>
           <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][desc_position]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.desc_position %>"/>
           <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][desc_background]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.desc_background %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][value_id]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.value_id %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][label]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.label %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][disabled]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="<%- data.disabled %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][media_type]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value="image"/>
           <input type="hidden"
                   name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][removed]"
                   data-form-part="<?php /* @escapeNotVerified */ echo $formName ?>"
                   value=""
                   class="is-removed"/>


            <div class="product-image-wrapper">
                <img class="product-image"
                     data-role="image-element"
                     src="<%- data.url %>"
                     alt="<%- data.label %>"/>

                <div class="actions">
                    <button type="button"
                            class="action-remove"
                            data-role="delete-button"
                            title="<?php /* @escapeNotVerified */ echo __('Delete image') ?>">
                    <span>
                        <?php /* @escapeNotVerified */ echo __('Delete image') ?>
                    </span>
                    </button>
                    <div class="draggable-handle"></div>
                </div>
                <div class="image-fade"><span><?php /* @escapeNotVerified */ echo __('Hidden') ?></span></div>
            </div>


            <div class="item-description">
                <div class="item-title" data-role="img-title"><%- data.label %></div>
                <div class="item-size">
                  <span data-role="image-dimens"></span>, <span data-role="image-size"><%- data.sizeLabel %></span>
                </div>
            </div>

            <ul class="item-roles" data-role="roles-labels">
                <?php
                foreach ($block->getImageTypes() as $typeData) {
                    ?>
                    <li data-role-code="<?php /* @escapeNotVerified */ echo $block->escapeHtml(
                        $typeData['code']
                    ) ?>" class="item-role item-role-<?php /* @escapeNotVerified */ echo $block->escapeHtml(
                        $typeData['code']
                    ) ?>">
                        <?php /* @escapeNotVerified */ echo $block->escapeHtml($typeData['label']) ?>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </script>

    <script data-role="img-dialog-container-tmpl" type="text/x-magento-template">
      <div class="image-panel" data-role="dialog">
      </div>
    </script>

    <script data-role="img-dialog-tmpl" type="text/x-magento-template">
            <div class="image-panel-preview">
                <img src="<%- data.url %>" alt="<%- data.label %>" />
            </div>
            <div class="image-panel-controls">
                <strong class="image-name"><%- data.label %></strong>

                <fieldset class="admin__fieldset fieldset-image-panel">

                    <div class="admin__field field-image-slide-enabled">
                        <label class="admin__field-label" for="slide-enabled">
                            <span><?php /* @escapeNotVerified */ echo __('Enabled')?></span>
                        </label>
                        <div class="admin__field-control">
                        <select id="slide-enabled" class="select admin__control-select"
                                name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][is_active]">
                            <?php foreach ($block->getActiveValues() as $value): ?>
                                <option <% if (data.is_active == '<?php echo $value["value"] ?>') { %>selected="selected"<% } %> value="<?php echo $value['value'] ?>">
                                    <?php echo $value["label"] ?>
                                </option>
                            <?php endforeach; ?> ?>
                        </select>
                        </div>
                    </div>

                    <div class="admin__field field-image-title">
                        <label class="admin__field-label" for="slide-title">
                            <span><?php /* @escapeNotVerified */ echo __('Title')?></span>
                        </label>
                        <div class="admin__field-control">
                        <input type="text"
                               id="slide-title"
                               class="edited-data input-text admin__control-text"
                               data-role="slide-title"
                               value="<%- data.title %>"
                               name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][title]"/>
                       </div>
                    </div>

                    <div class="admin__field field-image-title">
                        <label class="admin__field-label" for="slide-link">
                            <span><?php /* @escapeNotVerified */ echo __('Link')?></span>
                        </label>
                        <div class="admin__field-control">
                        <input type="text"
                               id="slide-link"
                               class="edited-data input-text admin__control-text"
                               data-role="slide-link"
                               value="<%- data.link %>"
                               name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][link]"/>
                       </div>
                    </div>

                    <div class="admin__field field-image-url-target">
                        <label class="admin__field-label" for="slide-link-target">
                            <span><?php /* @escapeNotVerified */ echo __('Open link in')?></span>
                        </label>
                        <div class="admin__field-control">
                        <select id="slide-link-target" class="select admin__control-select"
                                name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][target]">
                            <?php foreach ($block->getTargetValues() as $value): ?>
                                <option <% if (data.target == '<?php echo $value["value"] ?>') { %>selected="selected"<% } %> value="<?php echo $value['value'] ?>">
                                    <?php echo $value["label"] ?>
                                </option>
                            <?php endforeach; ?> ?>
                        </select>
                        </div>
                    </div>

                    <div class="admin__field field-image-description">
                        <label class="admin__field-label" for="slide-description">
                            <span><?php /* @escapeNotVerified */ echo __('Description')?></span>
                        </label>
                        <div class="admin__field-control">
                            <textarea id="slide-description" class="edited-data textarea admin__control-textarea" rows="3" name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][description]"><%- data.description %></textarea>
                        </div>
                    </div>

                    <div class="admin__field field-image-desc-position">
                        <label class="admin__field-label" for="slide-desc-position">
                            <span><?php /* @escapeNotVerified */ echo __('Description Position')?></span>
                        </label>
                        <div class="admin__field-control">
                        <select id="slide-desc-position" class="select admin__control-select"
                                name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][desc_position]">
                            <?php foreach ($block->getDescPosValues() as $value): ?>
                                <option <% if (data.desc_position == '<?php echo $value["value"] ?>') { %>selected="selected"<% } %> value="<?php echo $value['value'] ?>">
                                    <?php echo $value["label"] ?>
                                </option>
                            <?php endforeach; ?> ?>
                        </select>
                        </div>
                    </div>

                    <div class="admin__field field-image-desc-background">
                        <label class="admin__field-label" for="slide-desc-background">
                            <span><?php /* @escapeNotVerified */ echo __('Description Background')?></span>
                        </label>
                        <div class="admin__field-control">
                        <select id="slide-desc-background" class="select admin__control-select"
                                name="<?php /* @escapeNotVerified */ echo $elementName ?>[<%- data.file_id %>][desc_background]">
                            <?php foreach ($block->getDescBackValues() as $value): ?>
                                <option <% if (data.desc_background == '<?php echo $value["value"] ?>') { %>selected="selected"<% } %> value="<?php echo $value['value'] ?>">
                                    <?php echo $value["label"] ?>
                                </option>
                            <?php endforeach; ?> ?>
                        </select>
                        </div>
                    </div>

                    <div class="admin__field admin__field-inline field-image-size" data-role="size">
                        <label class="admin__field-label">
                            <span><?php /* @escapeNotVerified */ echo __('Image Size') ?></span>
                        </label>
                        <div class="admin__field-value" data-message="<?php /* @escapeNotVerified */ echo __('{size}') ?>"></div>
                    </div>

                    <div class="admin__field admin__field-inline field-image-resolution" data-role="resolution">
                        <label class="admin__field-label">
                            <span><?php /* @escapeNotVerified */ echo __('Image Resolution') ?></span>
                        </label>
                        <div class="admin__field-value" data-message="<?php /* @escapeNotVerified */ echo __('{width}^{height} px') ?>"></div>
                    </div>

                </fieldset>
            </div>
    </script>
    <?php //echo $block->getChildHtml('new-video'); ?>
</div>
<script>
var byteConvert = function(bytes) {
    if (isNaN(bytes)) {
        return '';
    }
    var symbols = ['bytes', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
    var exp = Math.floor(Math.log(bytes)/Math.log(2));
    if (exp < 1) {
        exp = 0;
    }
    var i = Math.floor(exp / 10);
    bytes = bytes / Math.pow(2, 10 * i);

    if (bytes.toString().length > bytes.toFixed(2).toString().length) {
        bytes = bytes.toFixed(2);
    }
    return bytes + ' ' + symbols[i];
};
</script>
